#define WIFI_SSID "YOUR_WIFI_ADDRESS"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define SERVER_ADDRESS "YOUR_SERVER_ADDRESS"
#define MQTT_PORT 1883
#define MQTT_USERNAME "YOUR_MQTT_USERNAME"
#define MQTT_PASSWORD "YOUR_MQTT_PASSWORD"