it.todo("implements auth systems in http api server")
it.todo("api/v1/getWateringLogs/:deviceId")
it.todo("change heartbeatInterval to 1 seconds?")
it.todo("add used devices_id database api/v1/getDevices")
it.todo("sanitize api param to prevent sql injection")
it.todo("swagger api docs?")
it.todo("add last seen database")
